In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('my_array', arr)

In [5]:
arr

array([0, 1, 2, 3, 4])

In [6]:
arr = np.arange(10)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [9]:
arr1 = np.load('my_array.npy')

In [10]:
arr2 = np.arange(10)

In [11]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1

array([0, 1, 2, 3, 4])

In [15]:
np.savez('ziparrays.npz', x=arr1, y=arr2)

In [18]:
archive_array = np.load('ziparrays.npz')

In [19]:
archive_array

In [20]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [21]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr = np.array([[1,2,3,4],[4,5,6,7]])

In [30]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [31]:
np.savetxt('my_test_text.txt', arr, delimiter=',')

In [35]:
!cat my_test_text.txt

'cat' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。


In [37]:
arr = np.loadtxt('my_test_text.txt', delimiter=',')

In [38]:
arr

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])