In [3]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [4]:
arr1 = np.arange(9).reshape((3,3))

In [5]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [9]:
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [13]:
concat_ser = pd.concat([ser1,ser2,ser1])

In [14]:
concat_ser

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [15]:
concat_ser['T']

T    0
T    0
dtype: int64

In [17]:
cs = pd.concat([ser1,ser2],axis=1)

In [18]:
cs

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [19]:
cs[0]

T    0.0
U    1.0
V    2.0
X    NaN
Y    NaN
Name: 0, dtype: float64

In [20]:
pd.concat([ser1,ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [21]:
pd.concat([ser1,ser2], axis=1, keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [22]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [23]:
dframe1

X         Y         Z
0 -0.443997 -1.023827  1.797222
1 -0.633859 -1.482607 -0.042381
2  0.602534  1.146572 -1.172492
3 -1.356176  1.588333  0.615527

In [24]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [25]:
dframe2

Y         Q         X
0 -0.330658  0.897339  1.449875
1  1.697161  0.286236  0.598591
2  0.411671  1.866146 -0.349858

In [27]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.443997 -1.023827  1.797222
1       NaN -0.633859 -1.482607 -0.042381
2       NaN  0.602534  1.146572 -1.172492
3       NaN -1.356176  1.588333  0.615527
0  0.897339  1.449875 -0.330658       NaN
1  0.286236  0.598591  1.697161       NaN
2  1.866146 -0.349858  0.411671       NaN

In [28]:
pd.concat([dframe1,dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.443997 -1.023827  1.797222
1       NaN -0.633859 -1.482607 -0.042381
2       NaN  0.602534  1.146572 -1.172492
3       NaN -1.356176  1.588333  0.615527
4  0.897339  1.449875 -0.330658       NaN
5  0.286236  0.598591  1.697161       NaN
6  1.866146 -0.349858  0.411671       NaN